name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
    - name: install funcraft
      run: |
        npm install @alicloud/fun -g
    - name: config
      run: |
        echo endpoint: 'https://5463858419226215.ap-northeast-1.fc.aliyuncs.com' > ~/.fcli/config.yaml
        echo api_version: '2016-08-15' >> ~/.fcli/config.yaml
        echo access_key_id: LTAI4Ftiwv1igVS2Whng3bfA >> ~/.fcli/config.yaml
        echo access_key_secret: ${{ secrets.ALICLOUD_TOKEN }} >> ~/.fcli/config.yaml
        echo security_token: '' >> ~/.fcli/config.yaml
        echo timeout: 60 >> ~/.fcli/config.yaml
        echo sls_endpoint: ap-northeast-1.log.aliyuncs.com >> ~/.fcli/config.yaml
